# Generated by Django 3.0.2 on 2020-01-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='Directions ... ', verbose_name='Directions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Ingredients ... ', verbose_name='Ingredients'),
        ),
    ]
