# Generated by Django 3.0.2 on 2020-01-27 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recette_app', '0012_auto_20200126_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date published')),
            ],
        ),
        migrations.AlterField(
            model_name='recette',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='travail_manuel',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='travail_manuel',
            name='materiel',
            field=models.TextField(verbose_name='Matériaux'),
        ),
        migrations.AlterField(
            model_name='travail_manuel',
            name='methode',
            field=models.TextField(verbose_name='Méthode'),
        ),
        migrations.AlterField(
            model_name='travail_manuel',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='travail_manuel',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='travail_manuel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
