# Generated by Django 3.0.2 on 2020-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette_app', '0008_auto_20200126_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travail_manuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('materiel', models.TextField()),
                ('methode', models.TextField()),
                ('pub_date', models.DateField(verbose_name='Date published')),
            ],
        ),
    ]
