# Generated by Django 3.0.2 on 2020-01-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette_app', '0009_travail_manuel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Recette',
        ),
    ]
