# Generated by Django 3.0.2 on 2020-01-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette_app', '0010_auto_20200126_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
