# Generated by Django 3.0.2 on 2020-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette_app', '0011_auto_20200126_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(verbose_name='Ingrédients'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='preparation',
            field=models.TextField(verbose_name='Préparation'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
